<?php
if (!defined('PROJECT_ROOT')) exit('No direct script access allowed');

$is_spa_request = isset($_SERVER['HTTP_X_SPA_REQUEST']) && $_SERVER['HTTP_X_SPA_REQUEST'] === 'true';
if (!$is_spa_request) {
    require_once PROJECT_ROOT . '/views/header.php';
}
?>

<div class="container mx-auto px-4 py-6">
    <div class="flex justify-between items-center mb-6">
        <h1 class="text-2xl font-bold text-gray-800 dark:text-white">Laporan Kolektibilitas Pinjaman</h1>
        <div class="flex gap-2">
            <button id="btn-export-pdf" class="bg-red-600 hover:bg-red-700 text-white font-semibold py-2 px-4 rounded-md transition duration-150 ease-in-out flex items-center gap-2">
                <i class="bi bi-file-earmark-pdf-fill"></i> PDF
            </button>
            <button id="btn-export-csv" class="bg-green-600 hover:bg-green-700 text-white font-semibold py-2 px-4 rounded-md transition duration-150 ease-in-out flex items-center gap-2">
                <i class="bi bi-file-earmark-excel-fill"></i> CSV
            </button>
        </div>
    </div>

    <div class="bg-white dark:bg-gray-800 shadow rounded-lg p-4 mb-6">
        <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div>
                <label for="filter-kolektibilitas" class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Status Kolektibilitas</label>
                <select id="filter-kolektibilitas" class="block w-full rounded-md border-gray-300 dark:bg-gray-700 dark:border-gray-600 shadow-sm focus:border-primary focus:ring-primary sm:text-sm">
                    <option value="">Semua</option>
                    <option value="Lancar">Lancar (0 hari)</option>
                    <option value="Dalam Perhatian Khusus">Dalam Perhatian Khusus (1-90 hari)</option>
                    <option value="Kurang Lancar">Kurang Lancar (91-120 hari)</option>
                    <option value="Diragukan">Diragukan (121-180 hari)</option>
                    <option value="Macet">Macet (> 180 hari)</option>
                </select>
            </div>
            <div>
                <label for="search-anggota" class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Cari Anggota / No Pinjaman</label>
                <input type="text" id="search-anggota" class="block w-full rounded-md border-gray-300 dark:bg-gray-700 dark:border-gray-600 shadow-sm focus:border-primary focus:ring-primary sm:text-sm" placeholder="Nama atau Nomor...">
            </div>
            <div class="flex items-end">
                <button id="btn-filter" class="w-full bg-primary hover:bg-primary-600 text-white font-semibold py-2 px-4 rounded-md transition duration-150 ease-in-out">
                    Tampilkan
                </button>
            </div>
        </div>
    </div>

    <div class="bg-white dark:bg-gray-800 shadow rounded-lg overflow-hidden">
        <div class="overflow-x-auto">
            <table class="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
                <thead class="bg-gray-50 dark:bg-gray-700">
                    <tr>
                        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider">Anggota</th>
                        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider">No. Pinjaman</th>
                        <th scope="col" class="px-6 py-3 text-right text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider">Plafon</th>
                        <th scope="col" class="px-6 py-3 text-right text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider">Sisa Pokok</th>
                        <th scope="col" class="px-6 py-3 text-center text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider">Tunggakan (Hari)</th>
                        <th scope="col" class="px-6 py-3 text-center text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider">Kolektibilitas</th>
                    </tr>
                </thead>
                <tbody id="laporan-table-body" class="bg-white dark:bg-gray-800 divide-y divide-gray-200 dark:divide-gray-700">
                    <!-- Rows generated by JS -->
                </tbody>
                <tfoot class="bg-gray-50 dark:bg-gray-700">
                    <tr>
                        <td colspan="3" class="px-6 py-3 text-right text-xs font-bold text-gray-900 dark:text-white uppercase">Total Sisa Pokok</td>
                        <td class="px-6 py-3 text-right text-xs font-bold text-gray-900 dark:text-white" id="total-sisa-pokok">Rp 0</td>
                        <td colspan="2"></td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>

<?php
if (!$is_spa_request) {
    require_once PROJECT_ROOT . '/views/footer.php';
}
?>